package com.springboot.outbox.domain.enums;

public enum EventType {
    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,
    TRANSACTION_APPROVED,
    TRANSACTION_REJECTED,
    EMBARGO_CHECK_REQUESTED,
    EMBARGO_CHECK_COMPLETED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED
}
